<label class="label" for="<?php echo $id ?? '' ?>">
    <?php echo $label ?? '' ?> <span class="text-muted"><?php echo $detail ?? '' ?></span>
</label>
<div class="input-group">
    <?php
    if (isset($prepend)) {
        ?>
        <div class="input-group-prepend">
            <span class="input-group-text"><?php echo $prepend ?></span>
        </div>
        <?php
    }
    ?>
    <input
      type="<?php echo $input ?? 'text' ?>"
      class="<?php echo $input ?? 'input' ?>"
      id="<?php echo $id ?? '' ?>"
      name="<?php echo $name ?? $id ?? '' ?>"
      placeholder="<?php echo $placeholder ?? '' ?>"
      value="<?php echo $value ?? '' ?>"
        <?php echo isset($required) ? 'required' : '' ?>
    >
    <?php
    if (isset($info)) {
        ?>
        <small
          class="text-muted"
          style="display: block; width: 100%;"
        ><?php echo $info; ?></small>
        <?php
    }
    ?>
    <div class="invalid-feedback help is-danger">
        <?php echo $invalidFeedback ?? 'Required field.' ?>
    </div>
</div>