<label
  class="label"
  for="<?php echo $id ?? '' ?>"
>
    <?php echo $label ?? '' ?> <span class="text-muted"><?php echo $detail ?? '' ?></span>
</label>
<div class="select is-fullwidth">
    <select
      class="<?php echo $class ?? '' ?>"
      id="<?php echo $id ?? '' ?>"
      name="<?php echo $name ?? $id ?? '' ?>"
        <?php echo isset($required) ? 'required' : '' ?>
    >
        <option value="">Choose...</option>
        <?php
        if (isset($options) && is_array($options)) {
            foreach ($options as $option) {
                $value = $option['value'] ?? '';
                $label = $option['label'] ?? '';
                ?>
                <option value="<?php echo $value; ?>"><?php echo $label; ?></option>
                <?php
            }
        }
        ?>
    </select>
</div>
<?php
if (isset($info)) {
    ?>
    <small class="text-muted"><?php echo $info; ?></small>
    <?php
}
?>
<div class="invalid-feedback help is-danger">
    <?php echo $invalidFeedback ?? 'Please select a valid option.' ?>
</div>