<?php

use App\Application\Template\Engine;

/** @var Engine $this */

?>
<form
  class="form form-grid needs-validation"
  novalidate=""
  method="post"
>
    <div class="field width-50">
        <?php $this->input($firstName); ?>
    </div>

    <div class="field width-50">
        <?php $this->input($lastName); ?>
    </div>

    <div class="field width-100">
        <?php $this->input($username); ?>
    </div>

    <div class="field width-100">
        <?php $this->input($email); ?>
    </div>

    <div class="field width-100">
        <?php $this->input($address); ?>
    </div>

    <div class="field width-100">
        <?php $this->input($address2); ?>
    </div>

    <div class="field width-40">
        <?php $this->select($country); ?>
    </div>
    <div class="field width-40">
        <?php $this->select($state); ?>
    </div>
    <div class="field width-20">
        <?php $this->input($zip); ?>
    </div>

    <div class="field width-100">
        <hr class="mb-4">
        <?php $this->checkbox($sameAddress); ?>
        <?php $this->checkbox($saveInfo); ?>
        <hr class="mb-3">
    </div>

    <div class="field width-100">
        <h4 class="mb-3">Payment</h4>
        <div class="d-block my-3">
            <?php $this->radio($paymentMethod); ?>
        </div>
    </div>

    <div class="field width-50">
        <?php $this->input($creditCardName); ?>
    </div>
    <div class="field width-50">
        <?php $this->input($creditCardNumber); ?>
    </div>

    <div class="field width-30">
        <?php $this->input($creditCardExpiration); ?>
    </div>
    <div class="field width-20">
        <?php $this->input($cvv); ?>
    </div>

    <div class="field width-100">
        <hr class="mb-4">

        <button
          class="button is-primary btn btn-primary btn-lg btn-block"
          type="submit"
        >
            Continue to checkout
        </button>
    </div>
</form>
