<!DOCTYPE html>
<!-- saved from url=(0069)https://bulmatemplates.github.io/bulma-templates/templates/cover.html -->
<html>
<head>
    <meta
      http-equiv="Content-Type"
      content="text/html; charset=UTF-8"
    >

    <meta
      http-equiv="X-UA-Compatible"
      content="IE=edge"
    >
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1"
    >
    <title>Cover - Free Bulma template</title>
    <link
      rel="shortcut icon"
      href="https://bulmatemplates.github.io/bulma-templates/images/fav_icon.png"
      type="image/x-icon"
    >
    <link
      rel="stylesheet"
      href="bulma/style/font-awesome.min.css"
    >
    <link
      href="bulma/style/font.css"
      rel="stylesheet"
    >
    <!-- Bulma Version 0.8.x-->
    <link
      rel="stylesheet"
      href="bulma/style/bulma.min.css"
    >
    <style type="text/css">
    html,
    body {
        font-family: 'Open Sans';
    }

    img {
        padding: 5px;
        border: 1px solid #ccc;
    }
    </style>
    <link
      href="assets/style/grid.css"
      rel="stylesheet"
    >
    <link
      href="assets/style/validation.css"
      rel="stylesheet"
    >
</head>

<body>
    <section class="hero is-fullheight is-default is-bold">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div class="navbar-brand">
                        <a
                          class="navbar-item"
                          href="https://bulmatemplates.github.io/bulma-templates/"
                        >
                            <img
                              src="bulma/img/bulma.png"
                              alt="Logo"
                            >
                        </a>
                        <span
                          class="navbar-burger burger"
                          data-target="navbarMenu"
                        >
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </div>
                    <div
                      id="navbarMenu"
                      class="navbar-menu"
                    >
                        <div class="navbar-end">
                            <div class="tabs is-right">
                                <ul>
                                    <li class="is-active">
                                        <a>Home</a>
                                    </li>
                                    <li>
                                        <a href="https://bulmatemplates.github.io/bulma-templates/templates/cover.html">
                                            Examples
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://bulmatemplates.github.io/bulma-templates/templates/cover.html">
                                            Features
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://bulmatemplates.github.io/bulma-templates/templates/cover.html">
                                            Team
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://bulmatemplates.github.io/bulma-templates/templates/cover.html">
                                            Help
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div class="hero-body">
            <div class="container">
                <div class="columns is-vcentered">
                    <div class="column is-8">
                        <?php $this->view('general/form.phtml', $checkout['fields']); ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="bulma/script/bulma.js"></script>

</body>
<style
  id="stylish-1"
  class="stylish"
  type="text/css"
>a[href*="/followers"] {
    display: none !important;
}

a[href*="/following"] {
    display: none !important;
}</style>
<style
  id="stylish-2"
  class="stylish"
  type="text/css"
>@media (min-width: 576px) {
    .board {
        width: 25%;
    }
}

.table-section.section-15 {
    flex: 0 0 30%;
}

@media (min-width: 768px) {
    .table-section.section-15 {
        max-width: 30%;
    }
}

.container-limited.limit-container-width {
    max-width: 1280px !important;
}

.d-flex.w-100.align-items-center.pb-2 > .bold.table-section:nth-last-child(-n+3) {
    display: none
}

.ci-variable-body-item.ci-variable-masked-item.table-section.section-20.mr-0.border-top-0 {
    display: none;
}

.border-top-0.ci-variable-body-item.ci-variable-protected-item.mr-0.section-20.table-section {
    display: none;
}

.dropdown.ci-variable-body-item.js-variable-environment-dropdown-wrapper {
    display: none;
}</style>
</html>