<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">© 2017-2019 Company Name</p>
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="https://getbootstrap.com/docs/4.4/examples/checkout/#">Privacy</a>
        </li>
        <li class="list-inline-item">
            <a href="https://getbootstrap.com/docs/4.4/examples/checkout/#">Terms</a>
        </li>
        <li class="list-inline-item">
            <a href="https://getbootstrap.com/docs/4.4/examples/checkout/#">Support</a>
        </li>
    </ul>
</footer>