<div class="col-md-8 order-md-1">
    <h4 class="mb-3">Billing address</h4>
    <form
      class="needs-validation"
      novalidate=""
    >
        <div class="row">
            <div class="col-md-6 mb-3">
                <?php $this->includes('bootstrap/components/input.phtml', $fields['firstName']); ?>
            </div>

            <div class="col-md-6 mb-3">
                <?php $this->includes('bootstrap/components/input.phtml', $fields['lastName']); ?>
            </div>
        </div>

        <div class="mb-3">
            <?php $this->includes('bootstrap/components/input-group.phtml', $fields['username']); ?>
        </div>

        <div class="mb-3">
            <?php $this->includes('bootstrap/components/input.phtml', $fields['email']); ?>
        </div>

        <div class="mb-3">
            <?php $this->includes('bootstrap/components/input.phtml', $fields['address']); ?>
        </div>

        <div class="mb-3">
            <?php $this->includes('bootstrap/components/input.phtml', $fields['address2']); ?>
        </div>

        <div class="row">
            <div class="col-md-5 mb-3">
                <?php $this->includes('bootstrap/components/select.phtml', $fields['country']); ?>
            </div>
            <div class="col-md-4 mb-3">
                <?php $this->includes('bootstrap/components/select.phtml', $fields['state']); ?>
            </div>
            <div class="col-md-3 mb-3">
                <?php $this->includes('bootstrap/components/input.phtml', $fields['zip']); ?>
            </div>
        </div>

        <hr class="mb-4">

        <?php $this->includes('bootstrap/components/checkbox.phtml', $fields['same-address']); ?>
        <?php $this->includes('bootstrap/components/checkbox.phtml', $fields['save-info']); ?>

        <hr class="mb-4">

        <h4 class="mb-3">Payment</h4>
        <div class="d-block my-3">
            <?php $this->includes('bootstrap/components/radio.phtml', $fields['paymentMethod']); ?>
        </div>

        <div class="row">
            <div class="col-md-6 mb-3">
                <?php $this->includes('bootstrap/components/input.phtml', $fields['creditCardName']); ?>
            </div>
            <div class="col-md-6 mb-3">
                <?php $this->includes('bootstrap/components/input.phtml', $fields['creditCardNumber']); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 mb-3">
                <?php $this->includes('bootstrap/components/input.phtml', $fields['creditCardExpiration']); ?>
            </div>
            <div class="col-md-3 mb-3">
                <?php $this->includes('bootstrap/components/input.phtml', $fields['cvv']); ?>
            </div>
        </div>
        <hr class="mb-4">
        <button
          class="btn btn-primary btn-lg btn-block"
          type="submit"
        >Continue to checkout
        </button>
    </form>
</div>