<div class="col-md-8 order-md-1">
    <h4 class="mb-3">Billing address</h4>
    <form
      class="needs-validation"
      novalidate=""
    >
        <div class="row">
            <div class="col-md-6 mb-3">
                <?php $this->input($firstName); ?>
            </div>

            <div class="col-md-6 mb-3">
                <?php $this->input($lastName); ?>
            </div>
        </div>

        <div class="mb-3">
            <?php $this->input($username); ?>
        </div>

        <div class="mb-3">
            <?php $this->input($email); ?>
        </div>

        <div class="mb-3">
            <?php $this->input($address); ?>
        </div>

        <div class="mb-3">
            <?php $this->input($address2); ?>
        </div>

        <div class="row">
            <div class="col-md-5 mb-3">
                <?php $this->select($country); ?>
            </div>
            <div class="col-md-4 mb-3">
                <?php $this->select($state); ?>
            </div>
            <div class="col-md-3 mb-3">
                <?php $this->input($zip); ?>
            </div>
        </div>

        <hr class="mb-4">

        <?php $this->checkbox($sameAddress); ?>
        <?php $this->checkbox($saveInfo); ?>

        <hr class="mb-4">

        <h4 class="mb-3">Payment</h4>
        <div class="d-block my-3">
            <?php $this->radio($paymentMethod); ?>
        </div>

        <div class="row">
            <div class="col-md-6 mb-3">
                <?php $this->input($creditCardName); ?>
            </div>
            <div class="col-md-6 mb-3">
                <?php $this->input($creditCardNumber); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 mb-3">
                <?php $this->input($creditCardExpiration); ?>
            </div>
            <div class="col-md-3 mb-3">
                <?php $this->input($cvv); ?>
            </div>
        </div>
        <hr class="mb-4">
        <button
          class="btn btn-primary btn-lg btn-block"
          type="submit"
        >Continue to checkout
        </button>
    </form>
</div>