<!DOCTYPE html>
<html lang="en">
<head>
    <meta
      http-equiv="Content-Type"
      content="text/html; charset=UTF-8"
    >

    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    >
    <meta
      name="description"
      content=""
    >
    <meta
      name="author"
      content="Mark Otto, Jacob Thornton, and Bootstrap contributors"
    >
    <meta
      name="generator"
      content="Jekyll v3.8.6"
    >
    <title>Checkout example · Bootstrap</title>

    <link
      rel="canonical"
      href="https://getbootstrap.com/docs/4.4/examples/checkout/"
    >

    <!-- Bootstrap core CSS -->
    <link
      href="bootstrap/style/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    >

    <!-- Favicons -->
    <link
      rel="apple-touch-icon"
      href="https://getbootstrap.com/docs/4.4/assets/img/favicons/apple-touch-icon.png"
      sizes="180x180"
    >
    <link
      rel="icon"
      href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon-32x32.png"
      sizes="32x32"
      type="image/png"
    >
    <link
      rel="icon"
      href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon-16x16.png"
      sizes="16x16"
      type="image/png"
    >
    <link
      rel="manifest"
      href="https://getbootstrap.com/docs/4.4/assets/img/favicons/manifest.json"
    >
    <link
      rel="mask-icon"
      href="https://getbootstrap.com/docs/4.4/assets/img/favicons/safari-pinned-tab.svg"
      color="#563d7c"
    >
    <link
      rel="icon"
      href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon.ico"
    >
    <meta
      name="theme-color"
      content="#563d7c"
    >

    <style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
    </style>
    <!-- Custom styles for this template -->
    <link
      href="script/form-validation.css"
      rel="stylesheet"
    >
</head>
<body class="bg-light">
    <div class="container">
        <div class="py-5 text-center">
            <img
              class="d-block mx-auto mb-4"
              src="bootstrap/img/bootstrap-solid.svg"
              alt=""
              width="72"
              height="72"
            >
            <h2>Checkout form</h2>
            <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form
                group has a validation state that can be triggered by attempting to submit the form without completing
                it.
            </p>
        </div>

        <div class="row">
            <?php $this->includes('bootstrap/cart.phtml'); ?>

            <?php $this->includes('bootstrap/form.phtml'); ?>
        </div>

        <?php $this->includes('bootstrap/footer.phtml'); ?>
    </div>
    <script
      src="bootstrap/script/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script
      src="bootstrap/script/bootstrap.bundle.min.js"
      integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm"
      crossorigin="anonymous"
    ></script>
    <script src="bootstrap/script/form-validation.js"></script>

</body>
<style
  id="stylish-1"
  class="stylish"
  type="text/css"
>a[href*="/followers"] {
    display: none !important;
}

a[href*="/following"] {
    display: none !important;
}</style>
<style
  id="stylish-2"
  class="stylish"
  type="text/css"
>@media (min-width: 576px) {
    .board {
        width: 25%;
    }
}

.table-section.section-15 {
    flex: 0 0 30%;
}

@media (min-width: 768px) {
    .table-section.section-15 {
        max-width: 30%;
    }
}

.container-limited.limit-container-width {
    max-width: 1280px !important;
}

.d-flex.w-100.align-items-center.pb-2 > .bold.table-section:nth-last-child(-n+3) {
    display: none
}

.ci-variable-body-item.ci-variable-masked-item.table-section.section-20.mr-0.border-top-0 {
    display: none;
}

.border-top-0.ci-variable-body-item.ci-variable-protected-item.mr-0.section-20.table-section {
    display: none;
}

.dropdown.ci-variable-body-item.js-variable-environment-dropdown-wrapper {
    display: none;
}</style>
</html>